### ISSUE TITLE
Install: Error Code 128

### ISSUE THREAD

**Issue by daJuels** [hortinstein/node-dash-button#62]
I'm trying to install node-dash-button on a RaspberryPi (stretch lite - debian 9.4) with this command:
`sudo npm install node-dash-button`

**This is the reply:**
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git submodule update -q --init --recursive
npm ERR! fatal: Could not change back to '/root/.npm/_cacache/tmp/git-clone-c06219b0': Permission denied
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-09-19T06_57_31_180Z-debug.log

**This is the content of /root/.npm/_logs/2018-09-19T06_57_31_180Z-debug.log:**
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install', 'node-dash-button' ]
2 info using npm@6.4.1
3 info using node@v10.10.0
4 verbose npm-session 5c2729c98d87554b
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/node-dash-button 432ms (from cache)
8 silly pacote tag manifest for node-dash-button@latest fetched in 494ms
9 timing stage:loadCurrentTree Completed in 1353ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 2ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 62ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule node-dash-button@0.6.1 checking installable status
17 silly fetchPackageMetaData error for pcap@git+https://github.com/mranney/node_pcap.git Command failed: /usr/bin/git submodule update -q --init --recursive
17 silly fetchPackageMetaData fatal: Could not change back to '/root/.npm/_cacache/tmp/git-clone-c06219b0': Permission denied
18 timing stage:rollbackFailedOptional Completed in 3ms
19 timing stage:runTopLevelLifecycles Completed in 4953ms
20 silly saveTree pi
20 silly saveTree ├─┬ homebridge-wol@3.2.4
20 silly saveTree │ ├─┬ ping@0.2.2
20 silly saveTree │ │ ├── q@1.5.1
20 silly saveTree │ │ └── underscore@1.9.1
20 silly saveTree │ └── wake_on_lan@0.0.4
20 silly saveTree ├── node-dash-button@0.6.1
20 silly saveTree ├── ping@0.2.2
20 silly saveTree ├── q@1.5.1
20 silly saveTree ├── underscore@1.9.1
20 silly saveTree └── wake_on_lan@0.0.4
21 verbose stack Error: Command failed: /usr/bin/git submodule update -q --init --recursive
21 verbose stack fatal: Could not change back to '/root/.npm/_cacache/tmp/git-clone-c06219b0': Permission denied
21 verbose stack
21 verbose stack     at ChildProcess.exithandler (child_process.js:289:12)
21 verbose stack     at ChildProcess.emit (events.js:182:13)
21 verbose stack     at maybeClose (internal/child_process.js:962:16)
21 verbose stack     at Socket.stream.socket.on (internal/child_process.js:381:11)
21 verbose stack     at Socket.emit (events.js:182:13)
21 verbose stack     at Pipe._handle.close (net.js:606:12)
22 verbose cwd /home/pi
23 verbose Linux 4.14.69-v7+
24 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "node-dash-button"
25 verbose node v10.10.0
26 verbose npm  v6.4.1
27 error code 128
28 error Command failed: /usr/bin/git submodule update -q --init --recursive

I've tried with node v8.10.0 and v10.10.0
npm version is 6.4.1

**sudo apt list --installed | grep libpcap:**
libpcap-dev/stable,now 1.8.1-3 all [installed]
libpcap0.8/stable,now 1.8.1-3 armhf [installed]
libpcap0.8-dbg/stable,now 1.8.1-3 armhf [installed]
libpcap0.8-dev/stable,now 1.8.1-3 armhf [installed]
libpcapnav0/stable,now 0.8-3 armhf [installed]
libpcapnav0-dev/stable,now 0.8-3 armhf [installed]

I've also tried to start from scratch - no difference

**Comment by jogilder** [comment]
I finally got this to work with stretch lite. I had to make sure that everything was up to date on the pi 
`
sudo apt-get install libpcap-dev

sudo apt-get update

sudo apt-get upgrade

sudo apt-get autoremove

sudo apt-get autoclean 
`
After a restart I was then able to finally import the node from the graphical interface. It was all quite painful.

**Comment by niccolospa** [comment]
the solution provided from @jogilder didn't work for me, @daJuels did you solve it?

**Comment by daJuels** [comment]
I didn't try it yet - my homebridge setup is more or less stable at the moment and the dash buttons are nonessential for me..

**Comment by jogilder** [comment]
To be honest even though I got beyond the install error I've had to stop using node-red. Another node couldn't recover from WiFi glitches so I've written a python script instead.
